import AppNav from '@/components/utils/appNav'
import Header from '@/components/desktop/utils/header'
import { ThemeContextProvider } from '@/context/themeContex'
import { EThemeColor } from '../../../types/enums-color-theme'
import { cookies } from 'next/headers'
import FetchUserInfo from '@/api/fetchUserInfo'
import '../globals.css'

import { Inter } from 'next/font/google'
import type { Metadata, Viewport } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'planner',
    description: 'Generated by create next app',
    manifest: '/manifest.json',
    icons: { apple: '/assets/apple-touch-icon.png', shortcut: '/assets/android-chrome-512x512.png' },
}

export const viewport: Viewport = {
    themeColor: '#6266f5'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    const { theme } = await FetchUserInfo()

    const token = cookies().get('token')?.value

    return (
        <>
            <html lang="pt-br" className='bg-weirdWhite'>
                <body className={`${inter.className} relative`}>
                    <section className='flex flex-col'>
                        <ThemeContextProvider initial={theme as EThemeColor}>
                            {token && <Header />}
                            <section className='flex'>
                                {token && <AppNav />}
                                {children}
                            </section>
                        </ThemeContextProvider>
                    </section>
                </body>
            </html>
        </>
    )
}
