services:

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planner_biblico_docker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    command: "npx prisma migrate dev && npm run dev"
    expose:
      - 3333
    ports:
      - "3333:3333"

volumes:
  pgdata:
    driver: local
