import '../globals.css'

import { Inter } from 'next/font/google'
import type { Metadata, Viewport } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'planner',
    description: 'Generated by create next app',
    manifest: '/manifest.json',
    icons: { apple: '/assets/apple-touch-icon.png', shortcut: '/assets/android-chrome-512x512.png' },
}

export const viewport: Viewport = {
    themeColor: '#6266f5'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <html lang="pt-br" className='bg-weirdWhite'>
                <body className={`${inter.className} flex relative`}>
                    {children}
                </body>
            </html>
        </>
    )
}
